In [5]:
# ---- Step 1: Load the dataset (already in your Colab files) ----
import pandas as pd
from IPython.display import display

# Adjust the path if it's not in the root directory,
# e.g. '/content/song_views.csv' or '/content/drive/MyDrive/.../song_views.csv'
df = pd.read_csv('song_views.csv')

print("Original data (first 10 rows):")
display(df.head(10))

# ---- Step 2: Binarize the listen_count column ----
# Rule: 0 -> 0 (no listens), any value > 0 -> 1 (listened)
df['listen_count_binary'] = (df['listen_count'] > 0).astype(int)

# ---- Step 3: View the result ----
print("\nBinarized data (first 15 rows):")
display(df.head(15))

# ---- Step 4 (optional): Save the binarized file back to your files ----
df.to_csv('song_views_binarized.csv', index=False)

Original data (first 10 rows):

,user_id,song_id,title,listen_count
0,b6b799f34a204bd928ea014c243ddad6d0be4f8f,SOBONKR12A58A7A7E0,You're The One,2
1,b41ead730ac14f6b6717b9cf8859d5579f3f8d4d,SOBONKR12A58A7A7E0,You're The One,0
2,4c84359a164b161496d05282707cecbd50adbfc4,SOBONKR12A58A7A7E0,You're The One,0
3,779b5908593756abb6ff7586177c966022668b06,SOBONKR12A58A7A7E0,You're The One,0
4,dd88ea94f605a63d9fc37a214127e3f00e85e42d,SOBONKR12A58A7A7E0,You're The One,0
5,68f0359a2f1cedb0d15c98d88017281db79f9bc6,SOBONKR12A58A7A7E0,You're The One,0
6,116a4c95d63623a967edf2f3456c90ebbf964e6f,SOBONKR12A58A7A7E0,You're The One,17
7,45544491ccfcdc0b0803c34f201a6287ed4e30f8,SOBONKR12A58A7A7E0,You're The One,0
8,e701a24d9b6c59f5ac37ab28462ca82470e27cfb,SOBONKR12A58A7A7E0,You're The One,68
9,edc8b7b1fd592a3b69c3d823a742e1a064abec95,SOBONKR12A58A7A7E0,You're The One,0

Binarized data (first 15 rows):

,user_id,song_id,title,listen_count,listen_count_binary
0,b6b799f34a204bd928ea014c243ddad6d0be4f8f,SOBONKR12A58A7A7E0,You're The One,2,1
1,b41ead730ac14f6b6717b9cf8859d5579f3f8d4d,SOBONKR12A58A7A7E0,You're The One,0,0
2,4c84359a164b161496d05282707cecbd50adbfc4,SOBONKR12A58A7A7E0,You're The One,0,0
3,779b5908593756abb6ff7586177c966022668b06,SOBONKR12A58A7A7E0,You're The One,0,0
4,dd88ea94f605a63d9fc37a214127e3f00e85e42d,SOBONKR12A58A7A7E0,You're The One,0,0
5,68f0359a2f1cedb0d15c98d88017281db79f9bc6,SOBONKR12A58A7A7E0,You're The One,0,0
6,116a4c95d63623a967edf2f3456c90ebbf964e6f,SOBONKR12A58A7A7E0,You're The One,17,1
7,45544491ccfcdc0b0803c34f201a6287ed4e30f8,SOBONKR12A58A7A7E0,You're The One,0,0
8,e701a24d9b6c59f5ac37ab28462ca82470e27cfb,SOBONKR12A58A7A7E0,You're The One,68,1
9,edc8b7b1fd592a3b69c3d823a742e1a064abec95,SOBONKR12A58A7A7E0,You're The One,0,0
10,fb41d1c374d093ab643ef3bcd70eeb258d479076,SOBONKR12A58A7A7E0,You're The One,1,1
11,cb8ed62245335312d58c97c1d5c68b4cac682afd,SOBONKR12A58A7A7E0,You're The One,0,0
12,3fd3acaa8dfeb94b0602a33085b44ebe80545dd2,SOBONKR12A58A7A7E0,You're The One,0,0
13,672a1973a091e8ed8f4d46e3a740621f5fa4176c,SOBONKR12A58A7A7E0,You're The One,0,0
14,8c0a675214831879573af98d632bf2684273e0d9,SOBONKR12A58A7A7E0,You're The One,0,0

In [2]:
import pandas as pd
from IPython.display import display

# ---- Step 0: Load the dataset (already in your Colab files) ----
df = pd.read_csv('Pokemon.csv')

print("Original data (first 10 rows):")
display(df.head(10))


# ===================================================================
# 1. INTERACTION FEATURES
# Combine two numeric columns to create a new feature that captures
# their combined effect. Example: Attack * Defense = "Battle Power",
# and Sp. Atk * Sp. Def = "Special Power".
# ===================================================================
df['Attack_Defense_Interaction'] = df['Attack'] * df['Defense']
df['SpAtk_SpDef_Interaction'] = df['Sp. Atk'] * df['Sp. Def']

print("\nAfter adding interaction features:")
display(df[['Name', 'Attack', 'Defense', 'Attack_Defense_Interaction',
            'Sp. Atk', 'Sp. Def', 'SpAtk_SpDef_Interaction']].head(10))


# ===================================================================
# 2. TRANSFORMING ORDINAL FEATURES
# 'Generation' has a natural order (Gen 1 < Gen 2 < ... < Gen 6),
# so we map it to integers instead of treating it as unordered text.
# ===================================================================
generation_map = {
    'Gen 1': 1,
    'Gen 2': 2,
    'Gen 3': 3,
    'Gen 4': 4,
    'Gen 5': 5,
    'Gen 6': 6
}
df['Generation_Ordinal'] = df['Generation'].map(generation_map)

print("\nAfter transforming 'Generation' into an ordinal feature:")
display(df[['Name', 'Generation', 'Generation_Ordinal']].head(10))


# ===================================================================
# 3. ONE-HOT ENCODING
# 'Type 1' is a categorical (nominal) feature with no natural order,
# so we one-hot encode it into separate binary columns.
# ===================================================================
df_encoded = pd.get_dummies(df, columns=['Type 1'], prefix='Type1')

print("\nAfter one-hot encoding 'Type 1' (first 10 rows, relevant columns):")
type1_cols = [c for c in df_encoded.columns if c.startswith('Type1_')]
display(df_encoded[['Name'] + type1_cols].head(10))


# ===================================================================
# Final combined dataframe with all new features
# ===================================================================
print("\nFinal dataframe with interaction, ordinal, and one-hot columns:")
display(df_encoded.head(10))

# Optional: save result
df_encoded.to_csv('Pokemon_transformed.csv', index=False)

Original data (first 10 rows):

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,Gen 1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,Gen 1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,Gen 1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,Gen 1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,Gen 1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,Gen 1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,Gen 1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,Gen 1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,Gen 1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,Gen 1,False

After adding interaction features:

,Name,Attack,Defense,Attack_Defense_Interaction,Sp. Atk,Sp. Def,SpAtk_SpDef_Interaction
0,Bulbasaur,49,49,2401,65,65,4225
1,Ivysaur,62,63,3906,80,80,6400
2,Venusaur,82,83,6806,100,100,10000
3,VenusaurMega Venusaur,100,123,12300,122,120,14640
4,Charmander,52,43,2236,60,50,3000
5,Charmeleon,64,58,3712,80,65,5200
6,Charizard,84,78,6552,109,85,9265
7,CharizardMega Charizard X,130,111,14430,130,85,11050
8,CharizardMega Charizard Y,104,78,8112,159,115,18285
9,Squirtle,48,65,3120,50,64,3200

After transforming 'Generation' into an ordinal feature:

                        Name Generation  Generation_Ordinal
0                  Bulbasaur      Gen 1                   1
1                    Ivysaur      Gen 1                   1
2                   Venusaur      Gen 1                   1
3      VenusaurMega Venusaur      Gen 1                   1
4                 Charmander      Gen 1                   1
5                 Charmeleon      Gen 1                   1
6                  Charizard      Gen 1                   1
7  CharizardMega Charizard X      Gen 1                   1
8  CharizardMega Charizard Y      Gen 1                   1
9                   Squirtle      Gen 1                   1

After one-hot encoding 'Type 1' (first 10 rows, relevant columns):

,Name,Type1_Bug,Type1_Dark,Type1_Dragon,Type1_Electric,Type1_Fairy,Type1_Fighting,Type1_Fire,Type1_Flying,Type1_Ghost,Type1_Grass,Type1_Ground,Type1_Ice,Type1_Normal,Type1_Poison,Type1_Psychic,Type1_Rock,Type1_Steel,Type1_Water
0,Bulbasaur,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
1,Ivysaur,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
2,Venusaur,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
3,VenusaurMega Venusaur,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
4,Charmander,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
5,Charmeleon,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
6,Charizard,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
7,CharizardMega Charizard X,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
8,CharizardMega Charizard Y,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
9,Squirtle,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True

Final dataframe with interaction, ordinal, and one-hot columns:

,#,Name,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,...,Type1_Ghost,Type1_Grass,Type1_Ground,Type1_Ice,Type1_Normal,Type1_Poison,Type1_Psychic,Type1_Rock,Type1_Steel,Type1_Water
0,1,Bulbasaur,Poison,318,45,49,49,65,65,45,...,False,True,False,False,False,False,False,False,False,False
1,2,Ivysaur,Poison,405,60,62,63,80,80,60,...,False,True,False,False,False,False,False,False,False,False
2,3,Venusaur,Poison,525,80,82,83,100,100,80,...,False,True,False,False,False,False,False,False,False,False
3,3,VenusaurMega Venusaur,Poison,625,80,100,123,122,120,80,...,False,True,False,False,False,False,False,False,False,False
4,4,Charmander,NaN,309,39,52,43,60,50,65,...,False,False,False,False,False,False,False,False,False,False
5,5,Charmeleon,NaN,405,58,64,58,80,65,80,...,False,False,False,False,False,False,False,False,False,False
6,6,Charizard,Flying,534,78,84,78,109,85,100,...,False,False,False,False,False,False,False,False,False,False
7,6,CharizardMega Charizard X,Dragon,634,78,130,111,130,85,100,...,False,False,False,False,False,False,False,False,False,False
8,6,CharizardMega Charizard Y,Flying,634,78,104,78,159,115,100,...,False,False,False,False,False,False,False,False,False,False
9,7,Squirtle,NaN,314,44,48,65,50,64,43,...,False,False,False,False,False,False,False,False,False,True

In [4]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from IPython.display import display

# ===================================================================
# PART 1: song_views.csv  ->  numerical column: listen_count
# ===================================================================
songs = pd.read_csv('song_views.csv')

print("song_views.csv - original data (first 10 rows):")
display(songs.head(10))

# ---- Standard Scaling (mean=0, std=1) ----
std_scaler = StandardScaler()
songs['listen_count_standard_scaled'] = std_scaler.fit_transform(songs[['listen_count']])

# ---- Min-Max Scaling (range 0 to 1) ----
minmax_scaler = MinMaxScaler()
songs['listen_count_minmax_scaled'] = minmax_scaler.fit_transform(songs[['listen_count']])

print("\nsong_views.csv - after Standard and Min-Max scaling (first 10 rows):")
display(songs[['title', 'listen_count',
               'listen_count_standard_scaled',
               'listen_count_minmax_scaled']].head(10))

songs.to_csv('song_views_scaled.csv', index=False)


items = pd.read_csv('item_popularity.csv')

print("\nitem_popularity.csv - original data:")
display(items)

# ---- Standard Scaling (mean=0, std=1) ----
items['pop_percent_standard_scaled'] = std_scaler.fit_transform(items[['pop_percent']])

# ---- Min-Max Scaling (range 0 to 1) ----
items['pop_percent_minmax_scaled'] = minmax_scaler.fit_transform(items[['pop_percent']])

print("\nitem_popularity.csv - after Standard and Min-Max scaling:")
display(items)

items.to_csv('item_popularity_scaled.csv', index=False)

song_views.csv - original data (first 10 rows):

,user_id,song_id,title,listen_count
0,b6b799f34a204bd928ea014c243ddad6d0be4f8f,SOBONKR12A58A7A7E0,You're The One,2
1,b41ead730ac14f6b6717b9cf8859d5579f3f8d4d,SOBONKR12A58A7A7E0,You're The One,0
2,4c84359a164b161496d05282707cecbd50adbfc4,SOBONKR12A58A7A7E0,You're The One,0
3,779b5908593756abb6ff7586177c966022668b06,SOBONKR12A58A7A7E0,You're The One,0
4,dd88ea94f605a63d9fc37a214127e3f00e85e42d,SOBONKR12A58A7A7E0,You're The One,0
5,68f0359a2f1cedb0d15c98d88017281db79f9bc6,SOBONKR12A58A7A7E0,You're The One,0
6,116a4c95d63623a967edf2f3456c90ebbf964e6f,SOBONKR12A58A7A7E0,You're The One,17
7,45544491ccfcdc0b0803c34f201a6287ed4e30f8,SOBONKR12A58A7A7E0,You're The One,0
8,e701a24d9b6c59f5ac37ab28462ca82470e27cfb,SOBONKR12A58A7A7E0,You're The One,68
9,edc8b7b1fd592a3b69c3d823a742e1a064abec95,SOBONKR12A58A7A7E0,You're The One,0

song_views.csv - after Standard and Min-Max scaling (first 10 rows):

,title,listen_count,listen_count_standard_scaled,listen_count_minmax_scaled
0,You're The One,2,0.061911,0.016260
1,You're The One,0,-0.152283,0.000000
2,You're The One,0,-0.152283,0.000000
3,You're The One,0,-0.152283,0.000000
4,You're The One,0,-0.152283,0.000000
5,You're The One,0,-0.152283,0.000000
6,You're The One,17,1.668360,0.138211
7,You're The One,0,-0.152283,0.000000
8,You're The One,68,7.130287,0.552846
9,You're The One,0,-0.152283,0.000000

item_popularity.csv - original data:

    item_id  pop_percent
0  it_01345      0.98324
1  it_03431      0.56123
2  it_04572      0.12098
3  it_98021      0.35476
4  it_01298      0.92101
5  it_90120      0.81212
6  it_10123      0.56502

item_popularity.csv - after Standard and Min-Max scaling:

,item_id,pop_percent,pop_percent_standard_scaled,pop_percent_minmax_scaled
0,it_01345,0.98324,1.266937,1.000000
1,it_03431,0.56123,-0.192561,0.510577
2,it_04572,0.12098,-1.715141,0.000000
3,it_98021,0.35476,-0.906626,0.271125
4,it_01298,0.92101,1.051718,0.927829
5,it_90120,0.81212,0.675128,0.801545
6,it_10123,0.56502,-0.179454,0.514972

In [6]:
# ===================================================================
# Fixed-Width Binning, Adaptive (Quantile) Binning, and Log Transform
# Dataset: fcc_2016_coder_survey_subset.csv
# ===================================================================

import pandas as pd
import numpy as np
from IPython.display import display

df = pd.read_csv('fcc_2016_coder_survey_subset.csv')

print("Original data (first 10 rows):")
display(df[['ID.x', 'Age', 'Income']].head(10))


# ===================================================================
# 1. FIXED-WIDTH BINNING  ->  on 'Age'
# Split Age into equal-width bins (e.g. every 10 years) with labels.
# ===================================================================
bin_edges = [0, 20, 30, 40, 50, 60, 100]
bin_labels = ['<20', '20-29', '30-39', '40-49', '50-59', '60+']

df['Age_fixed_bin'] = pd.cut(df['Age'], bins=bin_edges, labels=bin_labels, right=False)

print("\nAfter fixed-width binning on 'Age':")
display(df[['ID.x', 'Age', 'Age_fixed_bin']].head(10))

print("\nCount of respondents per fixed Age bin:")
display(df['Age_fixed_bin'].value_counts().sort_index())


# ===================================================================
# 2. ADAPTIVE BINNING (QUANTILE-BASED)  ->  on 'Income'
# Split Income into bins that each contain roughly the same number
# of observations, using quantiles instead of fixed cutoffs.
# ===================================================================
df['Income_adaptive_bin'] = pd.qcut(
    df['Income'],
    q=4,
    labels=['Low', 'Medium', 'High', 'Very High']
)

print("\nAfter adaptive (quantile) binning on 'Income':")
display(df[['ID.x', 'Income', 'Income_adaptive_bin']].head(10))

print("\nCount of respondents per adaptive Income bin:")
display(df['Income_adaptive_bin'].value_counts().sort_index())


# ===================================================================
# 3. LOG TRANSFORM  ->  on 'Income'
# Income is highly skewed (a few very high earners), so a log
# transform compresses the scale and makes the distribution more
# symmetric. We use log1p (log(1 + x)) to safely handle any zeros.
# ===================================================================
df['Income_log'] = np.log1p(df['Income'])

print("\nAfter log transform on 'Income':")
display(df[['ID.x', 'Income', 'Income_log']].head(10))

print("\nIncome skewness before vs after log transform:")
print("Original Income skew:", df['Income'].skew())
print("Log-transformed Income skew:", df['Income_log'].skew())


# ===================================================================
# Save the final result
# ===================================================================
df.to_csv('fcc_survey_transformed.csv', index=False)

Original data (first 10 rows):

                               ID.x   Age   Income
0  cef35615d61b202f1dc794ef2746df14  28.0  32000.0
1  323e5a113644d18185c743c241407754  22.0  15000.0
2  b29a1027e5cd062e654a63764157461d  19.0  48000.0
3  04a11e4bcb573a1261eb0d9948d32637  26.0  43000.0
4  9368291c93d5d5f5c8cdb1a575e18bec  20.0   6000.0
5  dd0e77eab9270e4b67c19b0d6bbf621b  34.0  40000.0
6  7599c0aa0419b59fd11ffede98a3665d  23.0  32000.0
7  6dff182db452487f07a47596f314bddc  35.0  40000.0
8  9dc233f8ed1c6eb2432672ab4bb39249  33.0  80000.0
9  265fa78a1fb2409ff5416aec3c4f950d  33.0  80000.0

After fixed-width binning on 'Age':

                               ID.x   Age Age_fixed_bin
0  cef35615d61b202f1dc794ef2746df14  28.0         20-29
1  323e5a113644d18185c743c241407754  22.0         20-29
2  b29a1027e5cd062e654a63764157461d  19.0           <20
3  04a11e4bcb573a1261eb0d9948d32637  26.0         20-29
4  9368291c93d5d5f5c8cdb1a575e18bec  20.0         20-29
5  dd0e77eab9270e4b67c19b0d6bbf621b  34.0         30-39
6  7599c0aa0419b59fd11ffede98a3665d  23.0         20-29
7  6dff182db452487f07a47596f314bddc  35.0         30-39
8  9dc233f8ed1c6eb2432672ab4bb39249  33.0         30-39
9  265fa78a1fb2409ff5416aec3c4f950d  33.0         30-39

Count of respondents per fixed Age bin:

Age_fixed_bin
<20      1266
20-29    6976
30-39    3641
40-49    1201
50-59     429
60+       100
Name: count, dtype: int64

After adaptive (quantile) binning on 'Income':

                               ID.x   Income Income_adaptive_bin
0  cef35615d61b202f1dc794ef2746df14  32000.0              Medium
1  323e5a113644d18185c743c241407754  15000.0                 Low
2  b29a1027e5cd062e654a63764157461d  48000.0                High
3  04a11e4bcb573a1261eb0d9948d32637  43000.0                High
4  9368291c93d5d5f5c8cdb1a575e18bec   6000.0                 Low
5  dd0e77eab9270e4b67c19b0d6bbf621b  40000.0                High
6  7599c0aa0419b59fd11ffede98a3665d  32000.0              Medium
7  6dff182db452487f07a47596f314bddc  40000.0                High
8  9dc233f8ed1c6eb2432672ab4bb39249  80000.0           Very High
9  265fa78a1fb2409ff5416aec3c4f950d  80000.0           Very High

Count of respondents per adaptive Income bin:

Income_adaptive_bin
Low          2008
Medium       1676
High         2116
Very High    1529
Name: count, dtype: int64

After log transform on 'Income':

                               ID.x   Income  Income_log
0  cef35615d61b202f1dc794ef2746df14  32000.0   10.373522
1  323e5a113644d18185c743c241407754  15000.0    9.615872
2  b29a1027e5cd062e654a63764157461d  48000.0   10.778977
3  04a11e4bcb573a1261eb0d9948d32637  43000.0   10.668979
4  9368291c93d5d5f5c8cdb1a575e18bec   6000.0    8.699681
5  dd0e77eab9270e4b67c19b0d6bbf621b  40000.0   10.596660
6  7599c0aa0419b59fd11ffede98a3665d  32000.0   10.373522
7  6dff182db452487f07a47596f314bddc  40000.0   10.596660
8  9dc233f8ed1c6eb2432672ab4bb39249  80000.0   11.289794
9  265fa78a1fb2409ff5416aec3c4f950d  80000.0   11.289794

Income skewness before vs after log transform:
Original Income skew: 1.9346068584736449
Log-transformed Income skew: -0.2308648777658154

In [7]:
# ===================================================================
# Bag of Words - Bigram (2-gram) Model
# Dataset: const.txt (the U.S. Constitution)
# ===================================================================

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from IPython.display import display

# ---- Step 1: Load the text file ----
with open('const.txt', 'r', encoding='utf-8', errors='ignore') as f:
    text = f.read()

# Split the document into "sentences" / chunks so BoW has multiple
# rows to compare (splitting on blank lines/paragraphs works well
# for a structured document like the Constitution).
documents = [p.strip().replace('\n', ' ') for p in text.split('\n\n') if p.strip()]

print(f"Number of text chunks (documents): {len(documents)}")
print("\nFirst 3 chunks:")
for doc in documents[:3]:
    print("-", doc[:150], "...\n")


# ===================================================================
# Step 2: Build the Bag of Words model using bigrams (2-grams)
# ngram_range=(2, 2) means only 2-word phrases are counted
# ===================================================================
vectorizer = CountVectorizer(ngram_range=(2, 2), stop_words='english')
bow_matrix = vectorizer.fit_transform(documents)

# Convert to a DataFrame for easy viewing
bow_df = pd.DataFrame(
    bow_matrix.toarray(),
    columns=vectorizer.get_feature_names_out()
)

print("\nBag of Words (Bigram) matrix shape:", bow_df.shape)
print("\nBag of Words (Bigram) table (first 10 rows, first 15 bigram columns):")
display(bow_df.iloc[:10, :15])


# ===================================================================
# Step 3: Most frequent bigrams across the whole document
# ===================================================================
bigram_totals = bow_df.sum(axis=0).sort_values(ascending=False)

print("\nTop 20 most frequent bigrams in the Constitution:")
display(bigram_totals.head(20))


# ===================================================================
# Optional: save results
# ===================================================================
bow_df.to_csv('const_bow_bigrams.csv', index=False)
bigram_totals.to_csv('const_top_bigrams.csv', header=['count'])

Number of text chunks (documents): 167

First 3 chunks:
- Provided by USConstitution.net ------------------------------ ...

- [Note: Repealed text is not noted in this version.  Spelling errors have been corrected in this version.  For an uncorrected, annotated version of the ...

- We the People of the United States, in Order to form a more perfect Union, establish Justice, insure domestic Tranquility, provide for the common defe ...


Bag of Words (Bigram) matrix shape: (167, 2372)

Bag of Words (Bigram) table (first 10 rows, first 15 bigram columns):

,10 powers,10 state,11 judicial,12 electors,13 slavery,14 persons,15 right,15th day,16 congress,17 senate,18 year,19 right,20 terms,20th day,21 eighteenth
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

Top 20 most frequent bigrams in the Constitution:

united states              85
vice president             36
states shall               30
president shall            23
state shall                22
congress shall             19
house representatives      17
shall power                14
representatives shall      11
president vice             11
office president           10
president united            9
senate shall                9
powers duties               9
states state                9
appropriate legislation     8
house shall                 8
power enforce               8
person shall                8
duties office               7
dtype: int64